# Usa una imagen base de MySQL
FROM mysql:latest

# Establece las variables de entorno para la base de datos
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=prestamos_escenarios
ENV MYSQL_USER=nombre_de_usuario
ENV MYSQL_PASSWORD=contraseña

# Copia tu script SQL de inicialización (si es necesario)
COPY ./script.sql /docker-entrypoint-initdb.d/

# Expón el puerto 3306
EXPOSE 3306